/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FoodBankEmployee.TransportationRole;

import FoodBankSystem.FoodBank.FoodBank;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author fjj1213
 */
public class TransportationDepartmentJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private FoodBank Foodbank;
    

    /**
     * Creates new form TruckManagementWorkJPanel
     */
    public TransportationDepartmentJPanel(JPanel userProcessContainer,FoodBank Foodbank) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.Foodbank=Foodbank;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TruckManagement = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Manage Truck");

        TruckManagement.setText("Truck Management");
        TruckManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruckManagementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(TruckManagement))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(TruckManagement)
                .addContainerGap(178, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TruckManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruckManagementActionPerformed
        // TODO add your handling code here:
        TruckManagementJPanel tmjp = new TruckManagementJPanel(userProcessContainer,Foodbank);
        userProcessContainer.add("ManageUserAccountJPanel", tmjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_TruckManagementActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TruckManagement;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
