/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FoodBankAdmin;

import FoodBankSystem.FoodBank.FoodBank;

import FoodBankSystem.Role.ShelterAdminRole;
import FoodBankSystem.Shelter.Shelter;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rui
 */
public class ManageShelterJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private FoodBank foodBank;

    /**
     * Creates new form ManageShelterJPanel
     * @param userProcessContainer
     * @param foodBank
     */
    public ManageShelterJPanel(JPanel userProcessContainer, FoodBank foodBank) {
        initComponents();
        this.foodBank=foodBank;
        this.userProcessContainer=userProcessContainer;
        populateShelterTable();
        popStateCombox();
    }

    
    public void populateShelterTable(){
        DefaultTableModel dtm = (DefaultTableModel)ShelterTable.getModel();
        dtm.setRowCount(0);
        
        for(Shelter shelter : foodBank.getShelterDirectory().getShelters())
        {
            Object[] row = new Object[3];
            row[0] = shelter;
            row[1] = shelter.getName();
            row[2] = shelter.getLocation().getCity();
            dtm.addRow(row);           
        }
    }
    
     public static String[] states = new String[]{
        "Alabama", "Alaska", "Arizona", "Arkansas", "California",
        "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
        "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas",
        "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts",
        "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana",
        "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico",
        "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma",
        "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
        "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia",
        "Wisconsin", "Wyoming"
    };
    
    private void popStateCombox()
    {
        stateCombox.removeAllItems();
        
        for (String s : states)
        {
            stateCombox.addItem(s);
        }       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        shelterNameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addressLine1Text = new javax.swing.JTextField();
        addressLine2Text = new javax.swing.JTextField();
        cityText = new javax.swing.JTextField();
        zipcodeText = new javax.swing.JTextField();
        createShelterButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShelterTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        removeShelterButton = new javax.swing.JButton();
        updateShelterButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        stateCombox = new javax.swing.JComboBox<>();
        passwordPassword = new javax.swing.JPasswordField();
        confirmPasswordPassword = new javax.swing.JPasswordField();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Manage Shelter");

        shelterNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                shelterNameTextFocusLost(evt);
            }
        });

        jLabel3.setText("Shelter Name");

        jLabel4.setText("Address Line 1");

        jLabel5.setText("Address Line 2");

        jLabel6.setText("City");

        jLabel7.setText("Zipcode");

        jLabel8.setText("State");

        createShelterButton.setText("Create Shelter");
        createShelterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createShelterButtonActionPerformed(evt);
            }
        });

        ShelterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Shelter ID", "Name", "City"
            }
        ));
        jScrollPane1.setViewportView(ShelterTable);

        jLabel9.setText("User Name");

        jLabel11.setText("Password");

        jLabel12.setText("Confirm Password");

        removeShelterButton.setText("Remove Shelter");
        removeShelterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeShelterButtonActionPerformed(evt);
            }
        });

        updateShelterButton.setText("Update Shelter Information");
        updateShelterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateShelterButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Create Shelter");

        stateCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cityText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(zipcodeText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addressLine2Text)
                                .addComponent(stateCombox, javax.swing.GroupLayout.Alignment.LEADING, 0, 207, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(35, 35, 35)
                            .addComponent(addressLine1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(confirmPasswordPassword)
                                .addComponent(passwordPassword))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(createShelterButton)
                            .addGap(225, 225, 225)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(45, 45, 45)
                                .addComponent(shelterNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(removeShelterButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateShelterButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeShelterButton)
                    .addComponent(updateShelterButton))
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shelterNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(passwordPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(confirmPasswordPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addressLine1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addressLine2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(zipcodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(stateCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createShelterButton)
                    .addComponent(backButton))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void removeShelterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeShelterButtonActionPerformed
        int selectedRow = ShelterTable.getSelectedRow();
        
        Shelter shelter = (Shelter)ShelterTable.getValueAt(selectedRow, 0);
        foodBank.getShelterDirectory().removeShelter(shelter);
        populateShelterTable();      
        
    }//GEN-LAST:event_removeShelterButtonActionPerformed

    private void updateShelterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateShelterButtonActionPerformed
        // TODO add your handling code here:
        int row = ShelterTable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a shelter to update", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Shelter s = (Shelter)ShelterTable.getValueAt(row,0);
        UpdateShelterJPanel upjp = new UpdateShelterJPanel(userProcessContainer, s, foodBank);
        userProcessContainer.add("ViewSupplier", upjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_updateShelterButtonActionPerformed

    private void createShelterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createShelterButtonActionPerformed
        String name = shelterNameText.getText().trim();
        String address1 = addressLine1Text.getText().trim();
        String address2 = addressLine2Text.getText().trim();
        String city = cityText.getText().trim();
        String zipcode=zipcodeText.getText().trim();
        String state=stateCombox.getSelectedItem().toString();
        String userName = userNameLabel.getText().trim();
        String password = String.valueOf(passwordPassword.getPassword());
        String cpassword = String.valueOf(confirmPasswordPassword.getPassword());
        
        if(!password.equals(cpassword))
        {
            JOptionPane.showMessageDialog(this, "Passwords don't match!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(name.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter a name", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else
        {   
           Shelter s=new Shelter(name);
           foodBank.getShelterDirectory().getShelters().add(s);
           foodBank.getUserAccountDirectory().addUserAccount(userName, password, s, new ShelterAdminRole());
           
           s.getLocation().setFirstLine(address1);
           s.getLocation().setSecondLine(address2);
           s.getLocation().setCity(city);
           s.getLocation().setState(state);
           s.getLocation().setZipcode(zipcode);
          
           populateShelterTable();
           JOptionPane.showMessageDialog(null, "Shelter Successfully added", "Warning'", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_createShelterButtonActionPerformed

    private void shelterNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_shelterNameTextFocusLost
        String shelterName = shelterNameText.getText();
        for (Shelter shelter : foodBank.getShelterDirectory().getShelters())
        {
            int n = 0;
            if (shelter.getName().equals(shelterName))
            {
                n = n + 1;
                shelterName = shelterName + n;
            }
        }
        userNameLabel.setText(shelterName);            
    }//GEN-LAST:event_shelterNameTextFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ShelterTable;
    private javax.swing.JTextField addressLine1Text;
    private javax.swing.JTextField addressLine2Text;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField cityText;
    private javax.swing.JPasswordField confirmPasswordPassword;
    private javax.swing.JButton createShelterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField passwordPassword;
    private javax.swing.JButton removeShelterButton;
    private javax.swing.JTextField shelterNameText;
    private javax.swing.JComboBox<String> stateCombox;
    private javax.swing.JButton updateShelterButton;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField zipcodeText;
    // End of variables declaration//GEN-END:variables
}
