/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FoodBankAdmin;

import FoodBankSystem.FoodBank.FoodBank;
import FoodBankSystem.Role.ActivityManagementRole;
import FoodBankSystem.Role.ShelterManagementRole;
import FoodBankSystem.Role.SupplierManagementRole;
import FoodBankSystem.Role.TransportationRole;
import FoodBankSystem.Staff.Employee.ActivityManagementEmployee;
import FoodBankSystem.Staff.Employee.Employee;
import FoodBankSystem.Staff.Employee.Employee.Type;
import FoodBankSystem.Staff.Employee.ShelterManagementEmployee;
import FoodBankSystem.Staff.Employee.SupplierManagementEmployee;
import FoodBankSystem.Staff.Employee.TransportationEmployee;
import FoodBankSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rui
 */
public class ManageEmployeeJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private FoodBank Foodbank;

    /**
     * Creates new form ManageEmployeeJPanel
     */
    public ManageEmployeeJPanel(JPanel userProcessContainer, FoodBank Foodbank) {
        initComponents();
        this.Foodbank=Foodbank;
        this.userProcessContainer=userProcessContainer;
        popDepartmentCombox();        
    }
    public void popDepartmentCombox(){
        deptCombox.removeAllItems();   
        for (Type t: Employee.Type.values())
        {
            deptCombox.addItem(t);
        }
    }
    private void popEmoloyeeTable(Employee.Type type)
    {
        DefaultTableModel dtm = (DefaultTableModel)EmployeeTable.getModel();
        dtm.setRowCount(0);
                   
        for (Employee employee : Foodbank.getStaffDirectory().getEmployeeDirectory().getEmployees())
        {
            if(employee.getDepartment().endsWith(type.getValue()))
            {
                Object row[] = new Object[2];
                row[0] = employee.getId();
                row[1] = employee;
                dtm.addRow(row);
            }
        } 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeTable = new javax.swing.JTable();
        createEmployeeButton = new javax.swing.JButton();
        removeEmployee = new javax.swing.JButton();
        pwPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        confirmPwPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        updateEmployeeButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        dateChooserCombox = new datechooser.beans.DateChooserCombo();
        backButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        deptCombox = new javax.swing.JComboBox();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Manage Employee");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        firstNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameTextFocusLost(evt);
            }
        });

        lastNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameTextFocusLost(evt);
            }
        });

        EmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Employee ID", "Name"
            }
        ));
        jScrollPane1.setViewportView(EmployeeTable);

        createEmployeeButton.setText("Create Employee");
        createEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployeeButtonActionPerformed(evt);
            }
        });

        removeEmployee.setText("Remove Employee");
        removeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmployeeActionPerformed(evt);
            }
        });

        jLabel5.setText("Password");

        jLabel6.setText("User Name");

        jLabel7.setText("Confirm Password");

        updateEmployeeButton.setText("Update Employee Infomation");
        updateEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Birthday");

        backButton.setText("back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel10.setText("Add New Employee");

        jLabel8.setText("Select Department");

        deptCombox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        deptCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptComboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(deptCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(removeEmployee)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(updateEmployeeButton))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(112, 112, 112))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel9))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(33, 33, 33)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(firstNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                                        .addComponent(lastNameText))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(dateChooserCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                            .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel7))
                                            .addGap(14, 14, 14)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(pwPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                                .addComponent(confirmPwPassword)))))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(createEmployeeButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(backButton))))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(deptCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeEmployee)
                            .addComponent(updateEmployeeButton))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(pwPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(confirmPwPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(dateChooserCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEmployeeButton)
                    .addComponent(backButton))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEmployeeActionPerformed
        int selectedRow = EmployeeTable.getSelectedRow();
        
        if(selectedRow >= 0)
        {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete this employee?", "Warning", JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION)
            {
                Employee e = (Employee) EmployeeTable.getValueAt(selectedRow, 1);
                Foodbank.getStaffDirectory().getEmployeeDirectory().removeEmployee(e);
                Employee.Type type = (Employee.Type) deptCombox.getSelectedItem();
                popEmoloyeeTable(type);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select an employee", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_removeEmployeeActionPerformed

    private void createEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployeeButtonActionPerformed

        String firstName = firstNameText.getText().trim();
        String lastName = lastNameText.getText().trim();
        String userName = userNameLabel.getText().trim();
        String password = String.valueOf(pwPassword.getPassword());
        String cpassword = String.valueOf(confirmPwPassword.getPassword());
                
        
        if(!password.equals(cpassword))
        {
            JOptionPane.showMessageDialog(this, "Password doesn't match!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(firstName.equals("") || lastName.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter first name and last name", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else
        {   
            Date birthday = dateChooserCombox.getSelectedDate().getTime();
            Type type = (Type) deptCombox.getSelectedItem();
            if(type != null)
            switch (type) {
                case ActivityManagement:{
                    ActivityManagementEmployee ne = new ActivityManagementEmployee(firstName, lastName, birthday);
                    UserAccount ua = Foodbank.getUserAccountDirectory().addUserAccount(userName, password, ne, new ActivityManagementRole());
                    Foodbank.getStaffDirectory().getEmployeeDirectory().addEmployee(ne);
                        break;
                    }
                case ShelterManagement:{
                    ShelterManagementEmployee fe = new ShelterManagementEmployee(firstName, lastName, birthday);
                    UserAccount ua = Foodbank.getUserAccountDirectory().addUserAccount(userName, password, fe, new ShelterManagementRole());
                    Foodbank.getStaffDirectory().getEmployeeDirectory().addEmployee(fe);
                        break;
                    }
                case SupplierManagement:{
                    SupplierManagementEmployee fe = new SupplierManagementEmployee(firstName, lastName, birthday);
                    UserAccount ua = Foodbank.getUserAccountDirectory().addUserAccount(userName, password, fe, new SupplierManagementRole());
                    Foodbank.getStaffDirectory().getEmployeeDirectory().addEmployee(fe);
                        break;
                    }
                case Transportation:{
                    TransportationEmployee fe = new TransportationEmployee(firstName, lastName, birthday);
                    UserAccount ua = Foodbank.getUserAccountDirectory().addUserAccount(userName, password, fe, new TransportationRole());
                    Foodbank.getStaffDirectory().getEmployeeDirectory().addEmployee(fe);
                        break;
                    }
                default:
                    break;
            } 
            popEmoloyeeTable(type);
            JOptionPane.showMessageDialog(null, "Employee Successfully added", "Warning'", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_createEmployeeButtonActionPerformed

    private void updateEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeButtonActionPerformed
        int selectedRow = EmployeeTable.getSelectedRow();
        
        if(selectedRow >= 0)
        {
            Employee e = (Employee) EmployeeTable.getValueAt(selectedRow, 1);
            EmployeeInfoJPanel mijp = new EmployeeInfoJPanel(userProcessContainer, e);
            userProcessContainer.add("mijp", mijp);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select an employee from table", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateEmployeeButtonActionPerformed

    private void firstNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameTextFocusLost
        userNameLabel.setText(firstNameText.getText().trim()+"."+lastNameText.getText().trim());
    }//GEN-LAST:event_firstNameTextFocusLost

    private void lastNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameTextFocusLost
        userNameLabel.setText(firstNameText.getText().trim()+"."+lastNameText.getText().trim());
    }//GEN-LAST:event_lastNameTextFocusLost

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void deptComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptComboxActionPerformed
        Employee.Type type = (Employee.Type) deptCombox.getSelectedItem();
        if(type != null)
        {
            popEmoloyeeTable(type);
        }
    }//GEN-LAST:event_deptComboxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmployeeTable;
    private javax.swing.JButton backButton;
    private javax.swing.JPasswordField confirmPwPassword;
    private javax.swing.JButton createEmployeeButton;
    private datechooser.beans.DateChooserCombo dateChooserCombox;
    private javax.swing.JComboBox deptCombox;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JPasswordField pwPassword;
    private javax.swing.JButton removeEmployee;
    private javax.swing.JButton updateEmployeeButton;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
