/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FoodBankAdmin;

import FoodBankSystem.FoodBank.FoodBank;
import FoodBankSystem.Shelter.Shelter;
import FoodBankSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author fjj1213
 */
public class UpdateShelterJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Shelter shelter;
    private FoodBank foodBank;
    /**
     * Creates new form UpdateShelterJPanel
     * @param userProcessContainer
     * @param shelter
     */
    public UpdateShelterJPanel(JPanel userProcessContainer, Shelter shelter, FoodBank foodBank) {
        initComponents();
        this.shelter=shelter;
        this.userProcessContainer=userProcessContainer;       
        this.foodBank = foodBank;
        showAllInfo();
    }

    public void showAllInfo()
    {
        shelterNametText.setEnabled(false);
        passwordPassword.setEnabled(false);
        confirmPasswordPassword.setEnabled(false);
        addressLine1Text.setEnabled(false);
        addressLine2Text.setEnabled(false);
        cityText.setEnabled(false);
        zipCodeText.setEnabled(false);
        stateCombox.setEnabled(false);
        saveButton.setEnabled(false);
        updateShelterButton.setEnabled(true);
        
        shelterNametText.setText(shelter.getName());        
        addressLine1Text.setText(shelter.getLocation().getFirstLine());
        addressLine2Text.setText(shelter.getLocation().getSecondLine());
        cityText.setText(shelter.getLocation().getCity());
        zipCodeText.setText(shelter.getLocation().getZipcode());
        stateCombox.setSelectedItem(shelter.getLocation().getState());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        shelterNametText = new javax.swing.JTextField();
        addressLine1Text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addressLine2Text = new javax.swing.JTextField();
        cityText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        zipCodeText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        updateShelterButton = new javax.swing.JButton();
        stateCombox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        passwordPassword = new javax.swing.JPasswordField();
        confirmPasswordPassword = new javax.swing.JPasswordField();

        jLabel3.setText("Shelter Name");

        jLabel4.setText("Address Line 1");

        jLabel5.setText("Address Line 2");

        jLabel6.setText("City");

        jLabel7.setText("Zipcode");

        jLabel8.setText("State");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Update Shelter Information");

        backButton.setText("back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        updateShelterButton.setText("Update Shelter");
        updateShelterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateShelterButtonActionPerformed(evt);
            }
        });

        stateCombox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Password");

        jLabel12.setText("Confirm Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(addressLine2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stateCombox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cityText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(zipCodeText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(saveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shelterNametText, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressLine1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordPassword)
                            .addComponent(confirmPasswordPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(updateShelterButton))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shelterNametText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(passwordPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(confirmPasswordPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addressLine1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addressLine2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(zipCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateShelterButton)
                    .addComponent(saveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        Component [] componentArray = userProcessContainer.getComponents();
        Component c = componentArray[componentArray.length-1];
        ManageShelterJPanel msjp = (ManageShelterJPanel) c;
        msjp.populateShelterTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
       
        String shelterName = shelterNametText.getName();
        String shelterAddress1=addressLine1Text.getText();
        String shelterAddress2=addressLine2Text.getText();
        String city=cityText.getText();
        String state=zipCodeText.getText();
        String zipcode= (String)stateCombox.getSelectedItem();
        String password = String.valueOf(passwordPassword.getPassword());
        String confirmPassword = String.valueOf(confirmPasswordPassword.getPassword());
        if (! password.equals(confirmPassword))
        {
            JOptionPane.showMessageDialog(this, "Password don't match", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        shelter.setName(shelterName);
        for(UserAccount ua : foodBank.getUserAccountDirectory().getUserAccounts())
        {
            if (ua.getOrganization().equals(shelter))
            {
                String op = ua.getPassword();

                if (op.equals(password))
                {
                    JOptionPane.showMessageDialog(this, "Password is same as previous one", "ERROR", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                else{
                    ua.setPassword(password);
                }
            }
        }
        shelter.getLocation().setFirstLine(shelterAddress1);
        shelter.getLocation().setSecondLine(shelterAddress2);
        shelter.getLocation().setCity(city);
        shelter.getLocation().setState(state);
        shelter.getLocation().setZipcode(zipcode);

        JOptionPane.showMessageDialog(null, "Shelter successfully updated");

        shelterNametText.setEnabled(false);
        passwordPassword.setEnabled(false);
        confirmPasswordPassword.setEnabled(false);
        addressLine1Text.setEnabled(false);
        addressLine2Text.setEnabled(false);
        cityText.setEnabled(false);
        zipCodeText.setEnabled(false);
        stateCombox.setEnabled(false);
        saveButton.setEnabled(false);
        updateShelterButton.setEnabled(true);        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void updateShelterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateShelterButtonActionPerformed
        shelterNametText.setEnabled(true);
        addressLine1Text.setEnabled(true);
        addressLine2Text.setEnabled(true);

        cityText.setEnabled(true);
        zipCodeText.setEnabled(true);
        stateCombox.setEnabled(true);

        saveButton.setEnabled(true);
        updateShelterButton.setEnabled(false);
    }//GEN-LAST:event_updateShelterButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressLine1Text;
    private javax.swing.JTextField addressLine2Text;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField cityText;
    private javax.swing.JPasswordField confirmPasswordPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField passwordPassword;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField shelterNametText;
    private javax.swing.JComboBox stateCombox;
    private javax.swing.JButton updateShelterButton;
    private javax.swing.JTextField zipCodeText;
    // End of variables declaration//GEN-END:variables
}
