/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FoodBankEmployee.SupplierMgtRole;

import FoodBankSystem.FoodBank.FoodBank;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rui
 */
public class SupplierManagementDeptJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierManagementDeptJPanel
     */
    private JPanel userProcessContainer;
    private FoodBank Foodbank;
    public SupplierManagementDeptJPanel(JPanel userProcessContainer,FoodBank Foodbank) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.Foodbank=Foodbank;
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ManageSupplierJPanel = new javax.swing.JButton();
        ManageInventoryJPanel = new javax.swing.JButton();
        ManageProductButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Supplier Management Department");

        ManageSupplierJPanel.setText("Manage Supplier");
        ManageSupplierJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageSupplierJPanelActionPerformed(evt);
            }
        });

        ManageInventoryJPanel.setText("Manage Inventory");
        ManageInventoryJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageInventoryJPanelActionPerformed(evt);
            }
        });

        ManageProductButton.setText("Manage Product");
        ManageProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ManageInventoryJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManageSupplierJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManageProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(ManageSupplierJPanel)
                .addGap(26, 26, 26)
                .addComponent(ManageInventoryJPanel)
                .addGap(29, 29, 29)
                .addComponent(ManageProductButton)
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ManageSupplierJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageSupplierJPanelActionPerformed
        // TODO add your handling code here:
        ManageSupplierJPanel msjp = new ManageSupplierJPanel(userProcessContainer,Foodbank);
        userProcessContainer.add("ManageUserAccountJPanel", msjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageSupplierJPanelActionPerformed

    private void ManageInventoryJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageInventoryJPanelActionPerformed
        // TODO add your handling code here:
        ManageInventoryJPanel mijp = new ManageInventoryJPanel(userProcessContainer,Foodbank);
        userProcessContainer.add("ManageUserAccountJPanel", mijp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageInventoryJPanelActionPerformed

    private void ManageProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageProductButtonActionPerformed
        // TODO add your handling code here:
        ManageProductCatalogJPanel mpcjp = new ManageProductCatalogJPanel(userProcessContainer,Foodbank);
        userProcessContainer.add("ManageProductCatalogJPanel", mpcjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageProductButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageInventoryJPanel;
    private javax.swing.JButton ManageProductButton;
    private javax.swing.JButton ManageSupplierJPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
