/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FoundationEmployee.Nutrition;

import FoodBankSystem.Foundation;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rui
 */
public class NutritionDeptJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NutritionDeptJPanel
     */
    JPanel userProcessContainer;
    Foundation foundation;
    
    public NutritionDeptJPanel(JPanel userProcessContainer, Foundation foundation) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.foundation = foundation;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createMenuButton = new javax.swing.JButton();
        viewUpdateMenuButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Nutrition Department");

        createMenuButton.setText("Create Menu");
        createMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMenuButtonActionPerformed(evt);
            }
        });

        viewUpdateMenuButton.setText("View/Update Menu");
        viewUpdateMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUpdateMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewUpdateMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(createMenuButton)
                .addGap(27, 27, 27)
                .addComponent(viewUpdateMenuButton)
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMenuButtonActionPerformed
        CreateMenuJPanel cmjp = new CreateMenuJPanel(userProcessContainer, foundation);
        userProcessContainer.add("CreateMenuJPanel", cmjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createMenuButtonActionPerformed

    private void viewUpdateMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUpdateMenuButtonActionPerformed
        ViewMenuJPanel vmjp = new ViewMenuJPanel(userProcessContainer, foundation);
        userProcessContainer.add("ViewMenuJPanel", vmjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewUpdateMenuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createMenuButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewUpdateMenuButton;
    // End of variables declaration//GEN-END:variables
}
