/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FoundationEmployee.Nutrition;

import FoodBankSystem.Menu.Menu;
import FoodBankSystem.Menu.MenuItem;
import FoodBankSystem.Supplier.Product.Product;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rui
 */
public class ViewMenuDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewMenuDetailJPanel
     */
    JPanel userProcessContainer;
    Menu menu;
    
    public ViewMenuDetailJPanel(JPanel userProcessContainer, Menu menu) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.menu = menu;
        popAllCombox();
        popAllInformation();
    }

    private void popAllCombox()
    {
        menuTypeCombox.removeAllItems();
        menuTypeCombox.addItem("Basic");
        menuTypeCombox.addItem("Nutritious");

        targetAgeCombox.removeAllItems();        
        for(Menu.AgeGroup agegroup : Menu.AgeGroup.values())
        {
            targetAgeCombox.addItem(agegroup.getValue());
        }                
        
        targetHealthConditionCombox.removeAllItems();
        targetHealthConditionCombox.addItem("Illness");
        targetHealthConditionCombox.addItem("Health");
        
        targetIncomeCombox.removeAllItems();
        for (Menu.AvgIncome avgIncome : Menu.AvgIncome.values())
        {
            targetIncomeCombox.addItem(avgIncome.getValue());
        }
                
        popStatesCombox();
        
        targetSeasonCombox.removeAllItems();
        targetSeasonCombox.addItem("Spring");
        targetSeasonCombox.addItem("Summer");
        targetSeasonCombox.addItem("Fall");
        targetSeasonCombox.addItem("Winter");
    }
    
    
    private void popAllInformation()
    {
        menuTypeCombox.setSelectedItem(menu.getType());
        targetAgeCombox.setSelectedItem(menu.getAgeGroup());
        targetHealthConditionCombox.setSelectedItem(menu.getHealthCondition());
        targetIncomeCombox.setSelectedItem(menu.getAvgIncome());
        targetStateCombox.setSelectedItem(menu.getState());
        targetSeasonCombox.setSelectedItem(menu.getSeason());
        
        if(menu.getGender().equals("Female"))
        {
            femaleRadioButton.setSelected(true);
        }else
        {
            maleRadioButton.setSelected(true);
        }
        
        popMenuTable();
        
    }
    
    private void popMenuTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)menuTable.getModel();
        dtm.setRowCount(0);
        for (MenuItem mi : menu.getMenuItemList().getMenuItems())
        {
            Object[] row = new Object[2];
            row[0] = mi;
            row[1] = mi.getQuantity();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        targetAgeCombox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        targetHealthConditionCombox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        targetIncomeCombox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        targetStateCombox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        menuTypeCombox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        addComponentButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        quantityText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        targetSeasonCombox = new javax.swing.JComboBox<>();
        backButton = new javax.swing.JButton();
        saveMenuButton = new javax.swing.JButton();
        deleteComponentButton = new javax.swing.JButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        maleRadioButton = new javax.swing.JRadioButton();
        foodNameText = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("View/Update Menu");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Basic Information");

        jLabel3.setText("Menu Type");

        jLabel4.setText("Target Age");

        targetAgeCombox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Target Health Condition");

        targetHealthConditionCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Target Gender");

        jLabel7.setText("Target Income");

        targetIncomeCombox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Target State");

        targetStateCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("Menu Detail");

        menuTypeCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Food Name", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(menuTable);

        addComponentButton.setText("Add Component");
        addComponentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComponentButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Food Name");

        jLabel11.setText("Quantity");

        jLabel12.setText("Target Season");

        targetSeasonCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        saveMenuButton.setText("Save Changes");
        saveMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuButtonActionPerformed(evt);
            }
        });

        deleteComponentButton.setText("Delete Component");
        deleteComponentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteComponentButtonActionPerformed(evt);
            }
        });

        femaleRadioButton.setText("Female");

        maleRadioButton.setText("Male");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(backButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel6))
                                    .addGap(134, 134, 134)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(femaleRadioButton)
                                            .addGap(18, 18, 18)
                                            .addComponent(maleRadioButton))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(saveMenuButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(targetSeasonCombox, 0, 122, Short.MAX_VALUE)
                                            .addComponent(targetIncomeCombox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(targetHealthConditionCombox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(targetAgeCombox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(targetStateCombox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(menuTypeCombox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(368, 368, 368)
                            .addComponent(deleteComponentButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(17, 17, 17))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quantityText, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(foodNameText))
                        .addGap(87, 87, 87)
                        .addComponent(addComponentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuTypeCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(targetAgeCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(targetHealthConditionCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(targetIncomeCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(femaleRadioButton)
                                .addComponent(maleRadioButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(targetStateCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(targetSeasonCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveMenuButton)
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteComponentButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addComponentButton)
                    .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addComponentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComponentButtonActionPerformed
        
        String foodName = foodNameText.getText();
        Product product = new Product(foodName);
        
        MenuItem menuItem = menu.getMenuItemList().addMenuItem(product);
        menuItem.setQuantity(Integer.parseInt(quantityText.getText()));
                       
        DefaultTableModel dtm = (DefaultTableModel)menuTable.getModel();
        dtm.setRowCount(0);
        
        for(MenuItem mi : menu.getMenuItemList().getMenuItems())
        {
            Object row[] = new Object[2];
            row[0] = mi.getProduct().getName();
            row[1] = mi.getQuantity();
            dtm.addRow(row);
        }        
    }//GEN-LAST:event_addComponentButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void saveMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuButtonActionPerformed
        //type
        menu.setType((String)menuTypeCombox.getSelectedItem());
        
        //age group
        if(targetAgeCombox.getSelectedItem().equals(Menu.AgeGroup.Youth1))
        {
            menu.setAgeGroup(Menu.AgeGroup.Youth1.getValue());
        }
        if(targetAgeCombox.getSelectedItem().equals(Menu.AgeGroup.Youth2))
        {
            menu.setAgeGroup(Menu.AgeGroup.Youth2.getValue());

        }
        if(targetAgeCombox.getSelectedItem().equals(Menu.AgeGroup.Youth3))
        {
            menu.setAgeGroup(Menu.AgeGroup.Youth3.getValue());

        }
        if(targetAgeCombox.getSelectedItem().equals(Menu.AgeGroup.Youth4))
        {
            menu.setAgeGroup(Menu.AgeGroup.Youth4.getValue());

        }
        if(targetAgeCombox.getSelectedItem().equals(Menu.AgeGroup.Adult1))
        {
            menu.setAgeGroup(Menu.AgeGroup.Adult1.getValue());

        }
        if(targetAgeCombox.getSelectedItem().equals(Menu.AgeGroup.Adult2))
        {
            menu.setAgeGroup(Menu.AgeGroup.Adult2.getValue());

        }
        if(targetAgeCombox.getSelectedItem().equals(Menu.AgeGroup.Adult3))
        {
            menu.setAgeGroup(Menu.AgeGroup.Adult3.getValue());

        }
        if(targetAgeCombox.getSelectedItem().equals(Menu.AgeGroup.Old1))
        {
            menu.setAgeGroup(Menu.AgeGroup.Old1.getValue());

        }
        if(targetAgeCombox.getSelectedItem().equals(Menu.AgeGroup.Old2))
        {
            menu.setAgeGroup(Menu.AgeGroup.Old2.getValue());

        }

        if(targetAgeCombox.getSelectedItem().equals(Menu.AgeGroup.Old3))
        {
            menu.setAgeGroup(Menu.AgeGroup.Old3.getValue());
        }
        
        //health condition
        menu.setHealthCondition((String)targetHealthConditionCombox.getSelectedItem());
        
        //gender
        String gender;
        boolean female = femaleRadioButton.isSelected();
        if (female == true)
        {
            gender = "Female";
            menu.setGender(gender);
        }
        else if (female == false)
        {
            gender = "Male";
            menu.setGender(gender);
        }
               
        //state
        menu.setState((String)targetStateCombox.getSelectedItem());
        
        //season
        menu.setSeason((String)targetSeasonCombox.getSelectedItem());
        
        //avg income
        if(targetIncomeCombox.getSelectedItem().equals(Menu.AvgIncome.Poverty1))
        {
            menu.setAvgIncome(Menu.AvgIncome.Poverty1.getValue());
        }
        if(targetIncomeCombox.getSelectedItem().equals(Menu.AvgIncome.Poverty2))
        {
            menu.setAvgIncome(Menu.AvgIncome.Poverty2.getValue());
        }
        if(targetIncomeCombox.getSelectedItem().equals(Menu.AvgIncome.Poverty3))
        {
            menu.setAvgIncome(Menu.AvgIncome.Poverty3.getValue());
        }
        if(targetIncomeCombox.getSelectedItem().equals(Menu.AvgIncome.Poverty4))
        {
            menu.setAvgIncome(Menu.AvgIncome.Poverty4.getValue());
        }
                
        JOptionPane.showMessageDialog(null, "Updates saved");
    }//GEN-LAST:event_saveMenuButtonActionPerformed

    private void deleteComponentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteComponentButtonActionPerformed
        int SelectedRow = menuTable.getSelectedRow();
        
        if (SelectedRow >= 0){
        MenuItem mi = (MenuItem)menuTable.getValueAt(SelectedRow, 0);
        menu.getMenuItemList().removeMenuItem(mi);
        popMenuTable();
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_deleteComponentButtonActionPerformed

    private void popStatesCombox()
    {
        targetStateCombox.removeAllItems();
        
        targetStateCombox.addItem("Alabama");
        targetStateCombox.addItem("Alaska");
        targetStateCombox.addItem("Arizona");
        targetStateCombox.addItem("Arkansas");
        targetStateCombox.addItem("California");
        targetStateCombox.addItem("Colorado");
        targetStateCombox.addItem("Connecticut");
        targetStateCombox.addItem("Delaware");
        targetStateCombox.addItem("Florida");
        targetStateCombox.addItem("Georgia");
        targetStateCombox.addItem("Hawaii");
        targetStateCombox.addItem("Idaho");
        targetStateCombox.addItem("Illinois");
        targetStateCombox.addItem("Indiana");
        targetStateCombox.addItem("Iowa");
        targetStateCombox.addItem("Kansas");
        targetStateCombox.addItem("Kentucky");
        targetStateCombox.addItem("Louisiana");
        targetStateCombox.addItem("Maine");
        targetStateCombox.addItem("Maryland");
        targetStateCombox.addItem("Massachusetts");
        targetStateCombox.addItem("Michigan");
        targetStateCombox.addItem("Minnesota");
        targetStateCombox.addItem("Mississippi");
        targetStateCombox.addItem("Missouri");
        targetStateCombox.addItem("Montana");
        targetStateCombox.addItem("Nebraska");
        targetStateCombox.addItem("Nevada");
        targetStateCombox.addItem("New Hampshire");
        targetStateCombox.addItem("New Jersey");
        targetStateCombox.addItem("New Mexico");
        targetStateCombox.addItem("New York");
        targetStateCombox.addItem("North Carolina");
        targetStateCombox.addItem("North Dakota");
        targetStateCombox.addItem("Ohio");
        targetStateCombox.addItem("Oklahoma");
        targetStateCombox.addItem("Oregon");
        targetStateCombox.addItem("Pennsylvania");
        targetStateCombox.addItem("Rhode Island");
        targetStateCombox.addItem("South Carolina");
        targetStateCombox.addItem("South Dakota");
        targetStateCombox.addItem("Tennessee");
        targetStateCombox.addItem("Texas");
        targetStateCombox.addItem("Utah");
        targetStateCombox.addItem("Vermont");
        targetStateCombox.addItem("Virginia");
        targetStateCombox.addItem("Washington");
        targetStateCombox.addItem("West Virginia");
        targetStateCombox.addItem("Wisconsin");
        targetStateCombox.addItem("Wyoming");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComponentButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteComponentButton;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JTextField foodNameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JTable menuTable;
    private javax.swing.JComboBox<String> menuTypeCombox;
    private javax.swing.JTextField quantityText;
    private javax.swing.JButton saveMenuButton;
    private javax.swing.JComboBox targetAgeCombox;
    private javax.swing.JComboBox<String> targetHealthConditionCombox;
    private javax.swing.JComboBox targetIncomeCombox;
    private javax.swing.JComboBox<String> targetSeasonCombox;
    private javax.swing.JComboBox<String> targetStateCombox;
    // End of variables declaration//GEN-END:variables
}
