/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.foundationadmin;

import FoodBankSystem.Foundation;
import FoodBankSystem.Role.FoundationFinancialRole;
import FoodBankSystem.Role.NutritionRole;
import FoodBankSystem.Staff.Employee.Employee;
import FoodBankSystem.Staff.Employee.Employee.Type;
import FoodBankSystem.Staff.Employee.FinancialEmployee;
import FoodBankSystem.Staff.Employee.NutritionEmployee;
import FoodBankSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rui
 */
public class ManageEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmployeeJPanel
     */
    
    JPanel userProcessContainer;
    Foundation foundation;
    
    public ManageEmployeeJPanel(JPanel userProcessContainer,Foundation foundation) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.foundation = foundation;
        popDepartmentCombox();
    }

    private void popDepartmentCombox()
    {
        deptCombox.removeAllItems();
        
        deptCombox.addItem(Employee.Type.Nutrition);        
        deptCombox.addItem(Employee.Type.FoundationFinancial);
    }
    
    private void popEmoloyeeTable(Type type)
    {
        DefaultTableModel dtm = (DefaultTableModel)employeeTable.getModel();
        dtm.setRowCount(0);
                   
        for (Employee employee : foundation.getStaffDirectory().getEmployeeDirectory().getEmployees())
        {
            if(employee.getDepartment().equals(type.getValue()))
            {
                Object row[] = new Object[2];
                row[0] = employee.getId();
                row[1] = employee;
                dtm.addRow(row);
            }
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        deptCombox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        createEmployeeButton = new javax.swing.JButton();
        removeEmployeeButton = new javax.swing.JButton();
        passwordText = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        confirmPasswordText = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        updateEmployeeInfoButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Manage Employee");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Department");

        firstNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameTextFocusLost(evt);
            }
        });

        lastNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameTextFocusLost(evt);
            }
        });

        deptCombox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        deptCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptComboxActionPerformed(evt);
            }
        });

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Employee ID", "Name"
            }
        ));
        jScrollPane1.setViewportView(employeeTable);

        createEmployeeButton.setText("Create Employee");
        createEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployeeButtonActionPerformed(evt);
            }
        });

        removeEmployeeButton.setText("Remove Employee");
        removeEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmployeeButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Password");

        jLabel6.setText("User Name");

        jLabel7.setText("Confirm Password");

        updateEmployeeInfoButton.setText("Update Employee Infomation");
        updateEmployeeInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeInfoButtonActionPerformed(evt);
            }
        });

        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Birthday");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(removeEmployeeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateEmployeeInfoButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createEmployeeButton)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel3)))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(confirmPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(backButton, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(deptCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(deptCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(removeEmployeeButton)
                                    .addComponent(updateEmployeeInfoButton))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel5))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)))
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEmployeeButton)
                    .addComponent(backButton))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deptComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptComboxActionPerformed
        Type type = (Type) deptCombox.getSelectedItem();
        if(type != null)
        {
            popEmoloyeeTable(type);
        }
    }//GEN-LAST:event_deptComboxActionPerformed

    private void removeEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEmployeeButtonActionPerformed
        int selectedRow = employeeTable.getSelectedRow();
        
        if(selectedRow >= 0)
        {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete this employee?", "Warning", JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION)
            {
                Employee e = (Employee) employeeTable.getValueAt(selectedRow, 1);
                foundation.getStaffDirectory().getEmployeeDirectory().removeEmployee(e);
                Type type = (Type) deptCombox.getSelectedItem();
                popEmoloyeeTable(type);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select a row from table", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_removeEmployeeButtonActionPerformed

    private void createEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployeeButtonActionPerformed
        String firstName = firstNameText.getText().trim();
        String lastName = lastNameText.getText().trim();
        String userName = jLabelUserName.getText().trim();
        String password = String.valueOf(passwordText.getPassword());
        String cpassword = String.valueOf(confirmPasswordText.getPassword());
        
        if(!password.equals(cpassword))
        {
            JOptionPane.showMessageDialog(this, "Passwords doesn't match!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(firstName.equals("") || lastName.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter first name and last name", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else
        {
            Date birthday = dateChooserCombo1.getSelectedDate().getTime();
            Type type = (Type) deptCombox.getSelectedItem();
            if(type == Employee.Type.Nutrition)
            {
                NutritionEmployee ne = new NutritionEmployee(firstName, lastName, birthday);            
                UserAccount ua = foundation.getUserAccountDirectory().addUserAccount(userName, password, ne, new NutritionRole());
                foundation.getStaffDirectory().getEmployeeDirectory().addEmployee(ne);
            }
            else if(type == Employee.Type.FoundationFinancial)
            {
                FinancialEmployee fe = new FinancialEmployee(firstName, lastName, birthday);
                UserAccount ua = foundation.getUserAccountDirectory().addUserAccount(userName, password, fe, new FoundationFinancialRole());
                foundation.getStaffDirectory().getEmployeeDirectory().addEmployee(fe);
            }
            popEmoloyeeTable(type);
        }
    }//GEN-LAST:event_createEmployeeButtonActionPerformed

    private void firstNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameTextFocusLost
        jLabelUserName.setText(firstNameText.getText().trim()+"."+lastNameText.getText().trim());
    }//GEN-LAST:event_firstNameTextFocusLost

    private void lastNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameTextFocusLost
        jLabelUserName.setText(firstNameText.getText().trim()+"."+lastNameText.getText().trim());
    }//GEN-LAST:event_lastNameTextFocusLost

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void updateEmployeeInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeInfoButtonActionPerformed
        int selectedRow = employeeTable.getSelectedRow();
        
        if(selectedRow >= 0)
        {
            Employee e = (Employee) employeeTable.getValueAt(selectedRow, 1);
            EmployeeInfoJPanel mijp = new EmployeeInfoJPanel(userProcessContainer, e);
            userProcessContainer.add("mijp", mijp);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select a row from table", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateEmployeeInfoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPasswordField confirmPasswordText;
    private javax.swing.JButton createEmployeeButton;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JComboBox deptCombox;
    private javax.swing.JTable employeeTable;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JButton removeEmployeeButton;
    private javax.swing.JButton updateEmployeeInfoButton;
    // End of variables declaration//GEN-END:variables
}
