/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FoodBankEmployee.EventMgtRole;

import FoodBankSystem.FoodBank.FoodBank;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rui
 */

public class EventManageDeptJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EventManageDeptJPanel
     */
    
    JPanel userProcessContainer;
    FoodBank foodbank;
    
    public EventManageDeptJPanel(JPanel userProcessContainer, FoodBank foodbank) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.foodbank = foodbank;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createEventButton = new javax.swing.JButton();
        viewManageEventButton = new javax.swing.JButton();
        manageVolunteerButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Event Management Department");

        createEventButton.setText("Create Event");
        createEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEventButtonActionPerformed(evt);
            }
        });

        viewManageEventButton.setText("View/Managet Event");
        viewManageEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewManageEventButtonActionPerformed(evt);
            }
        });

        manageVolunteerButton.setText("Manage Volunteer");
        manageVolunteerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVolunteerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageVolunteerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewManageEventButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createEventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(createEventButton)
                .addGap(18, 18, 18)
                .addComponent(viewManageEventButton)
                .addGap(18, 18, 18)
                .addComponent(manageVolunteerButton)
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEventButtonActionPerformed
        CreateEventJPanel cejp = new CreateEventJPanel(userProcessContainer, foodbank);
        userProcessContainer.add("CreateEventJPanel", cejp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createEventButtonActionPerformed

    private void viewManageEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewManageEventButtonActionPerformed
        ViewManageEventJPanel vmejp = new ViewManageEventJPanel(userProcessContainer, foodbank);
        userProcessContainer.add("ViewManageEventJPanel", vmejp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewManageEventButtonActionPerformed

    private void manageVolunteerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVolunteerButtonActionPerformed
        ManageVolunteerJPanel mvjp = new ManageVolunteerJPanel(userProcessContainer, foodbank);
        userProcessContainer.add("ManageVolunteerJPanel", mvjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageVolunteerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createEventButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageVolunteerButton;
    private javax.swing.JButton viewManageEventButton;
    // End of variables declaration//GEN-END:variables
}
