/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FoodBankEmployee.EventMgtRole;

import FoodBankSystem.Person.Address;
import FoodBankSystem.Person.Name;
import FoodBankSystem.Staff.Volunteer;
import java.awt.CardLayout;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rui
 */
public class ViewVolunteerDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewVolunteerDetailJPanel
     */
    JPanel userProcessContainer;
    Volunteer volunteer;
    
    public ViewVolunteerDetailJPanel(JPanel userProcessContainer,Volunteer volunteer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.volunteer = volunteer;
        
        popAllInformation(); 
        
        firstNameText.setEnabled(false);
        birthDateCombo.setEnabled(false);
        txtAddress1.setEnabled(false);
        txtAddress2.setEnabled(false);
        txtCity.setEnabled(false);
        stateComx.setEnabled(false);
        txtZip.setEnabled(false);
        phoneNumberText.setEnabled(false);
        emailAddressText.setEnabled(false);
        futureContactCheckBox.setEnabled(false);
        saveButton.setEnabled(false);
        
               
    }

    private void popAllInformation()
    {
        Calendar cal = Calendar.getInstance();
        cal.setTime(volunteer.getBirthday());
        
        firstNameText.setText(volunteer.getName().getFirstName());
        lastNameText.setText(volunteer.getName().getLastName());
        birthDateCombo.setSelectedDate(cal);
        txtAddress1.setText(volunteer.getAddress().getFirstLine());
        txtAddress2.setText(volunteer.getAddress().getSecondLine());
        txtCity.setText(volunteer.getAddress().getCity());
        stateComx.setSelectedItem(volunteer.getAddress().getState());
        txtZip.setText(volunteer.getAddress().getZipcode());
        phoneNumberText.setText(volunteer.getPhoneNum());
        emailAddressText.setText(volunteer.getEmail());
        futureContactCheckBox.setSelected(volunteer.isFuturContact());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        emailAddressText = new javax.swing.JTextField();
        phoneNumberText = new javax.swing.JTextField();
        firstNameText = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        futureContactCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        birthDateCombo = new datechooser.beans.DateChooserCombo();
        jLabel3 = new javax.swing.JLabel();
        lastNameText = new javax.swing.JTextField();
        txtZip = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JTextField();
        txtAddress2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        City = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        stateComx = new javax.swing.JComboBox();

        jLabel2.setText("First Name");

        jLabel4.setText("Date of Birth");

        jLabel6.setText("Phone Number");

        jLabel7.setText("Email Address");

        updateButton.setText("Update Information");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        futureContactCheckBox.setText("Future Contact");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("View Volunteer Detail");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Last Name");

        jLabel9.setText("Line 1:");

        jLabel10.setText("Line 2:");

        City.setText("City:");

        jLabel11.setText("Zip Code:");

        jLabel12.setText("State:");

        stateComx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(phoneNumberText, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(emailAddressText)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(City)
                                            .addComponent(jLabel10)))
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lastNameText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                            .addComponent(firstNameText))
                                        .addGap(102, 102, 102))
                                    .addComponent(stateComx, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtZip, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCity, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAddress2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAddress1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(birthDateCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateButton)
                            .addComponent(futureContactCheckBox)
                            .addComponent(saveButton)
                            .addComponent(backButton))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(birthDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(City))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateComx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emailAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(futureContactCheckBox)
                .addGap(28, 28, 28)
                .addComponent(updateButton)
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        
        firstNameText.setEnabled(true);
        birthDateCombo.setEnabled(true);
        txtAddress1.setEnabled(true);
        txtAddress2.setEnabled(true);
        txtCity.setEnabled(true);
        stateComx.setEnabled(true);
        txtZip.setEnabled(true);
        phoneNumberText.setEnabled(true);
        emailAddressText.setEnabled(true);
        futureContactCheckBox.setEnabled(true);
        saveButton.setEnabled(true);
        updateButton.setEnabled(false);
        backButton.setEnabled(false);                
    }//GEN-LAST:event_updateButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        
        String firstName = firstNameText.getText();
        String lastName = lastNameText.getText();
        Name name = new Name(firstName, lastName);        
        Date birthDate = birthDateCombo.getSelectedDate().getTime();
        
        Address address = new Address();
        address.setFirstLine(txtAddress1.getText());
        address.setFirstLine(txtAddress2.getText());
        address.setCity(txtCity.getText());
        address.setState((String)stateComx.getSelectedItem());
        address.setZipcode(txtZip.getText());
        
        String phoneNumber = phoneNumberText.getText();
        String emailAddress = emailAddressText.getText();
        boolean futureContact = futureContactCheckBox.isSelected();
        
        volunteer.setName(name);
        volunteer.setBirthday(birthDate);
        volunteer.setAddress(address);
        volunteer.setPhoneNum(phoneNumber);
        volunteer.setEmail(emailAddress);
        volunteer.setFuturContact(futureContact);
                
        firstNameText.setEnabled(false);
        birthDateCombo.setEnabled(false);
        txtAddress1.setEnabled(false);
        txtAddress2.setEnabled(false);
        txtCity.setEnabled(false);
        stateComx.setEnabled(false);
        txtZip.setEnabled(false);
        phoneNumberText.setEnabled(false);
        emailAddressText.setEnabled(false);
        futureContactCheckBox.setEnabled(false);
        saveButton.setEnabled(false);
        updateButton.setEnabled(true);
        backButton.setEnabled(true);
        
        JOptionPane.showMessageDialog(null, "Changes saved");

    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel City;
    private javax.swing.JButton backButton;
    private datechooser.beans.DateChooserCombo birthDateCombo;
    private javax.swing.JTextField emailAddressText;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JCheckBox futureContactCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JTextField phoneNumberText;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox stateComx;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtZip;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
