/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FoodBankEmployee.EventMgtRole;

import FoodBankSystem.Activity.Activity;
import FoodBankSystem.FoodBank.FoodBank;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rui
 */
public class ViewManageEventJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewEventJPanel
     */
    private JPanel userProcessContainer;
    private FoodBank foodbank;
    
    public ViewManageEventJPanel(JPanel userProcessContainer,FoodBank foodbank) {
        initComponents();
        this.userProcessContainer = userProcessContainer;        
        this.foodbank = foodbank;
        
        eventTypeCombox.removeAllItems();
        popEventCombox();
    }

    public void popEventCombox()
    {        
        eventTypeCombox.addItem("Funding raising");
        eventTypeCombox.addItem("Advertising Campaign");
        eventTypeCombox.addItem("Hiring");
        eventTypeCombox.addItem("Volunteer Activities");      
    }
    
    public void popEventTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)eventTable.getModel();
        dtm.setRowCount(0);
        
        for (Activity activity : foodbank.getActivityDirectory().getActivities())
        {
            if (activity.getType().equals(eventTypeCombox.getSelectedItem()))
            {
                Object[] row = new Object[3];
                row[0] = activity;
                row[1] = activity.getDate();
                row[2] = activity.getName();
                dtm.addRow(row);
            } 
        }       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        viewEventDetailButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        eventTypeCombox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        viewEventDetailButton.setText("View Event Detail");
        viewEventDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEventDetailButtonActionPerformed(evt);
            }
        });

        eventTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Event ID", "Event Date", "Event Name"
            }
        ));
        jScrollPane1.setViewportView(eventTable);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("View/Manage Event");

        eventTypeCombox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        eventTypeCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventTypeComboxActionPerformed(evt);
            }
        });

        jLabel2.setText("Select Event");

        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(105, 105, 105)
                        .addComponent(viewEventDetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(eventTypeCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventTypeCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewEventDetailButton)
                    .addComponent(backButton))
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void viewEventDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEventDetailButtonActionPerformed
        int SelectedRow = eventTable.getSelectedRow();
        
        if (SelectedRow >= 0){
            Activity activity = (Activity)eventTable.getValueAt(SelectedRow, 0);
            ViewEventDetailJPanel vedj = new ViewEventDetailJPanel(userProcessContainer, activity, foodbank);
            userProcessContainer.add("ViewEventDetailJPanel", vedj);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
                
    }//GEN-LAST:event_viewEventDetailButtonActionPerformed

    private void eventTypeComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventTypeComboxActionPerformed
        String eventType = (String) eventTypeCombox.getSelectedItem();
        if(eventType != null)
        {
            popEventTable();
        }
    }//GEN-LAST:event_eventTypeComboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTable eventTable;
    private javax.swing.JComboBox eventTypeCombox;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewEventDetailButton;
    // End of variables declaration//GEN-END:variables
}
