/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FoundationEmployee.FoundationFinancial;

import FoodBankSystem.Foundation;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Cuishaowen
 */
public class FoundationFinancialWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form Foundation
     */
    
    private JPanel userProcessContainer;
    private Foundation foundation;
    
    public FoundationFinancialWorkArea(JPanel userProcessContainer, Foundation foundation) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.foundation = foundation;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnReceive = new javax.swing.JButton();
        btnRecord = new javax.swing.JButton();
        btnDistributeFunds = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Foundation Financial Work Area");

        btnReceive.setText("Receive Donation From Food Banks");
        btnReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiveActionPerformed(evt);
            }
        });

        btnRecord.setText("Donation Record");
        btnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordActionPerformed(evt);
            }
        });

        btnDistributeFunds.setText("Distribute Funds");
        btnDistributeFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistributeFundsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReceive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDistributeFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addComponent(btnReceive)
                .addGap(18, 18, 18)
                .addComponent(btnRecord)
                .addGap(18, 18, 18)
                .addComponent(btnDistributeFunds)
                .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiveActionPerformed
        ReceiveDonationJPanel receiveDonationJPanel = new ReceiveDonationJPanel(userProcessContainer, foundation);
        userProcessContainer.add("receiveDonationJPanel", receiveDonationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReceiveActionPerformed

    private void btnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordActionPerformed
        DonationRecordJPanel donationRecordJPanel = new DonationRecordJPanel(userProcessContainer, foundation);
        userProcessContainer.add("donationRecordJPanel", donationRecordJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRecordActionPerformed

    private void btnDistributeFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistributeFundsActionPerformed
        DistributeFundsJPanel distributeFundsJPanel = new DistributeFundsJPanel(userProcessContainer, foundation);
        userProcessContainer.add("distributeFundsJPanel", distributeFundsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDistributeFundsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDistributeFunds;
    private javax.swing.JButton btnReceive;
    private javax.swing.JButton btnRecord;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
